name: 'Build & Test'
on:
  push:
    branches:
      - master
      - release/**
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.ref_name || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node: ['22', '24']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/cache@v6
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: ${{ github.ref == 'refs/heads/master' && 'production' }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - uses: actions/cache@v6
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        env:
          CRAFT_BUILD_SHA: ${{ github.sha }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build
      - name: Smoke Test
        run: ./dist/craft --help
      - name: NPM Pack
        run: npm pack
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: craft-binary
          path: |
            ${{ github.workspace }}/*.tgz
            ${{ github.workspace }}/dist/craft

