name: 'Build & Test'
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.ref_name || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node: ${{ github.actor == 'dependabot[bot]' && fromJSON('["24"]') || fromJSON('["22", "24"]') }}
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/cache@v6
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - uses: actions/cache@v6
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Smoke Test
        run: ./dist/craft --help
